version: '3.8'

services: 
  app: 
    build:
      context: node
    container_name: node
    networks:
      - fullcycle
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  nginx:
    restart: always
    build: 
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - fullcycle
    depends_on:
      - app

networks:
  fullcycle:
    driver: bridge