version: '3.8'

services: 
  app: 
    build:
      context: node
    container_name: node
    networks:
      - fullcycle
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - 3306
    healthcheck:
      test: curl -f https://db:3306 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  nginx:
    restart: always
    build: 
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - fullcycle
    depends_on:
      app:
        condition: service_started
        restart: true

networks:
  fullcycle:
    driver: bridge